### ISSUE TITLE
rwm_init() for RFM12B missing !!!

### ISSUE THREAD

**Issue by mpruessmeier** [openenergymonitor/emonTxFirmware#10]
Hi, when i compile the sketch with RFM12B defined and RFM69CW undefined I get the error...

emonTxV3_4_3Phase_Voltage.cpp.o: In function `setup':
/opt/arduino/emonTxV3_4_3Phase_Voltage.ino:264: undefined reference to `rfm_init()'
emonTxV3_4_3Phase_Voltage.cpp.o: In function `loop':
/opt/arduino/emonTxV3_4_3Phase_Voltage.ino:325: undefined reference to `rfm_send(unsigned char const*, unsigned char, unsigned char, unsigned char)'
collect2: error: ld returned 1 exit status
Multiple libraries were found for "Ports.h"
 Used: /home/mcp/Programming/Arduino/sketchbook/libraries/jeelib
 Not used: /home/mcp/Programming/Arduino/sketchbook/libraries/RFu_jeelib
Fehler beim Kompilieren.

We have original ordered EmonTX 3.4 with RFM12B Chip.

**Comment by glynhudson** [comment]
Are you using the latest JeeLib: https://github.com/jcw/jeelib. Do the other emonTx V3.4 examples compile for you e.g: https://github.com/openenergymonitor/emonTxFirmware/blob/master/emonTxV3/RFM/emonTxV3.4/emonTxV3_4_DiscreteSampling/emonTxV3_4_DiscreteSampling.ino

Be sure to set #define RF69_COMPAT 0 if using RFM12B

**Comment by tzapu** [comment]
hi,

i am getting this in https://github.com/openenergymonitor/emonTxFirmware/blob/master/emonTxV3/RFM/emonTxV3.4/emonTxV3_4_3Phase_Voltage/emonTxV3_4_3Phase_Voltage.ino

which does not need JeeLib as far as i can tell. there s no define for RFM12B just #ifdef RFM69CW

**Comment by glynhudson** [comment]
Please try again now, I have just updated the sketch. It seems part of the sketch was missing. There was an error when I committed last time to Github. Apologies, please let me know if issue has been fixed. No 3-phase example does not require github

**Comment by tzapu** [comment]
Hi, gave this a spin. It seems to pass the init phase, but it locks up when trying to transmit
```
emonTx V3.2 & V3.4 CT1234 Voltage 3 Phase example
Using RFM12B Radio
OpenEnergyMonitor.org
Node: 10 Freq: 868MHz Network: 210
Total Samples: 308 Power Samples: 252 Time: 242 Crossings: 22
284.29 
195.10 
93.01 
-6.98 
-373.43 
-377.06 
-362.71 
-282.43 
-194.24 
-92.15 
7.84 
86.76 
178.58 
252.33 
321.02 
367.66 
373.30 
376.93 
363.57 
Voltage: 242.09
 Phase 1: 0.26 A, -2.35 W, 61.92 VA, PF=-0.038
 Phase 2: 0.00 A, 0.00 W, 0.00 VA, PF=nan
 Phase 3: 0.00 A, 0.00 W, 0.00 VA, PF=nan
```

and that s all it does. I have tried filling the payload only with 0 to see if it was invalid values tripping it up, but the same result.

**Comment by glynhudson** [comment]
Oh dear, please could you post on the OpenEnergyMonitor forums. The 3-phase
sketch as been developed and maintained by members of the community. We
should be able to offer better support via the forums
http://openenergymonitor.org/emon/forum/5

On 16 November 2015 at 09:20, tzapu <notifications@github.com> wrote:

> Hi, gave this a spin. It seems to pass the init phase, but it locks up
> when trying to transmit
>
> emonTx V3.2 & V3.4 CT1234 Voltage 3 Phase example
> Using RFM12B Radio
> OpenEnergyMonitor.org
> Node: 10 Freq: 868MHz Network: 210
> Total Samples: 308 Power Samples: 252 Time: 242 Crossings: 22
> 284.29
> 195.10
> 93.01
> -6.98
> -373.43
> -377.06
> -362.71
> -282.43
> -194.24
> -92.15
> 7.84
> 86.76
> 178.58
> 252.33
> 321.02
> 367.66
> 373.30
> 376.93
> 363.57
> Voltage: 242.09
>  Phase 1: 0.26 A, -2.35 W, 61.92 VA, PF=-0.038
>  Phase 2: 0.00 A, 0.00 W, 0.00 VA, PF=nan
>  Phase 3: 0.00 A, 0.00 W, 0.00 VA, PF=nan
>
> and that s all it does. I have tried filling the payload only with 0 to
> see if it was invalid values tripping it up, but the same result.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openenergymonitor/emonTxFirmware/issues/10#issuecomment-156963618>
> .
>



-- 
Glyn Hudson

http://megni.co.uk
http://adventuresplusnorthwales.blogspot.com

**Comment by tzapu** [comment]
ok, thank you

**Comment by tzapu** [comment]
well, just as s pointer while i work things out, for me at least it seems that it might be because the sketches that did work, worked with RFu_JeeLib.h and this has parts of  JeeLib.h included

**Comment by tzapu** [comment]
an update, for RFμ 328 v1.2 and v1.3 there is a fix provided by Robert Wall. 
Replace a couple of defined with:
```
#define RFMSELPIN 4
#define RFMIRQPIN 3
```
discussion here http://openenergymonitor.org/emon/node/6349#comment-35999

i guess this can now be closed
thanks

**Comment by glynhudson** [comment]
No problem, glad you got the issue sorted.
