### ISSUE TITLE
update comments for number of samples (1662 instead of old 1480)

### ISSUE THREAD

**Issue by BbaassTMH** [openenergymonitor/emonTxFirmware#11]
We are still running emonTxV3.4 firmware V1.6, and as I was looking at firmware V2.3 I noticed that the number of samples for calculating apparent power was changed from 1480 to 1662.
But on line 350 and furher, the comments still say 1480.
https://github.com/openenergymonitor/emonTxFirmware/blob/master/emonTxV3/RFM/emonTxV3.4/emonTxV3_4_DiscreteSampling/emonTxV3_4_DiscreteSampling.ino#L350
Just thought I'd point it out.

**Comment by officeboy** [comment]
It is in the changelog comments,
V2.0 30/09/15 Update number of samples 1480 > 1662 to improve sampling
accurancy: 1662 samples take 300 mS, which equates to 15 cycles @ 50 Hz or
18 cycles @ 60 Hz.

**Comment by BbaassTMH** [comment]
What I meant was the old number of samples is mentioned while the new number of samples is actually used.
Doesn't change how things work, but the comments should probably match the actual code instead of the old code.
![untitled](https://cloud.githubusercontent.com/assets/5411443/12790321/0b952ef0-caa2-11e5-86bd-9d9133ec1ea6.png)
